### ISSUE TITLE
request "could hide modal by id"?

### ISSUE THREAD

**Issue by thearabbit** [PeppeL-G/bootstrap-3-modal#7]
I would like to request to hide modal by `modal id`.
Ex

``` js
// Template
<div class="modal fade" id="modal-student">
...........

// Js
Modal.hide('modal-student');
```

**Comment by PeppeL-G** [comment]
In Bootstrap, only one modal can be shown at a time, and `Modal.hide()` hides that one. Using ids do not contribute in any way.

**Comment by thearabbit** [comment]
because now i test with modal in modal (multi level pop up), it is work fine.
so i request this option like default option on bootstrap:

```
$('#myModal').modal('hide')
```

**Comment by PeppeL-G** [comment]
I can change so the call to `Modal.show` returns the jQuery object containing the modal, so you can do something like this:

``` javascript
$myModal1 = Modal.show('modal1TemplateName') // Show the first modal.
$myModal2 = Modal.show('modal2TemplateName') // Show the second modal.

$myModal2.hide() // Hide the second modal.
$myModal1.hide() // Hide the first modal.
```

However, this goes against issue https://github.com/PeppeL-G/bootstrap-3-modal/issues/2 :/ I guess disallowing/allowing multiple modals can be a customizable option.

Does this sound like a good solution to you?

**Comment by thearabbit** [comment]
thanks.

**Comment by PeppeL-G** [comment]
Second thoughts; it's probably in the modal's events you won't to close the modal, so the suggested way is probably quite useless. But I just published a new version of the package, where it's possible to insert multiple modals. See [this in the readme file](https://github.com/PeppeL-G/bootstrap-3-modal#using-multiple-modals). Please let me know if that doesn't work for you.

**Comment by thearabbit** [comment]
The first very thanks you, It work fine for multiple modals but it still have some problem when more click (duplicate). and then i try create `btn close` on all of modals (modal 1, modal 2, modal 3), i can close the `modal 3`, but i can not  close `modal 2` and `modal 1` (can close the last only). 

``` js
'click #btnModal1Close': function () {
        Modal.hide('templateModal1');
    }
......
'click #btnModal2Close': function () {
        Modal.hide('templateModal2');
    }
......
'click #btnModal3Close': function () {
        Modal.hide('templateModal3');
    }
```

**Comment by PeppeL-G** [comment]
It's the template instance you should send to `Modal.hide`, so it should look something like this:

``` javascript
'click #btnModal1Close': function (event, template) {
        Modal.hide(template);
    }
......
'click #btnModal2Close': function (event, template) {
        Modal.hide(template);
    }
......
'click #btnModal3Close': function (event, template) {
        Modal.hide(template);
    }
```

Passing the template instance instead of (for example) the id of the modal to `Modal.hide` allows multiple instances of the same modal template to be be shown at a a time.

**Comment by arist0tl3** [comment]
I know this is a year later than the thread was opened, but if anyone is still running into issues with closing modals after being one or two modals away:

Use a standard button with an id inside of the modal you want to target for closure:

`<button id="closeModalOne" type="button" class="btn btn-default" data-dismiss="modal">Close</button>`

And use js/jQuery to close it from anywhere in your app:

`$('#closeModalOne').click();`

A bit hacky, but it's the only way I could get modals to close after losing the context....

**Comment by thearabbit** [comment]
Thanks, now I close.
